FROM golang:1.26-alpine AS builder

RUN apk add --no-cache git make gcc musl-dev linux-headers

WORKDIR /app

RUN git clone https://github.com/ethereum/go-ethereum.git .
RUN make geth

FROM alpine:3.19

RUN apk add --no-cache ca-certificates

COPY --from=builder /app/build/bin/geth /usr/local/bin/geth

EXPOSE 8545 8546 30303

ENTRYPOINT ["geth"]