version: "3.9"

services:
  geth-devnet:
    image: ghcr.io/sbakurdzhiev/geth-dev:latest
    container_name: geth-devnet

    ports:
      - "8545:8545"
      - "30303:30303"

    volumes:
      - ./devnet-data:/root/.ethereum

    command:
      [
        "--dev",
        "--dev.period","1",
        "--http",
        "--http.addr","0.0.0.0",
        "--http.port","8545",
        "--http.api","eth,net,web3,personal",
        "--http.corsdomain","*",
        "--http.vhosts","*"
      ]