FROM ghcr.io/sbakurdzhiev/geth-dev:latest

COPY devnet-data /root/.ethereum

EXPOSE 8545 8546 30303

ENTRYPOINT ["geth"]

CMD ["--dev", "--http", "--http.addr", "0.0.0.0", "--http.port", "8545", "--http.api", "eth,net,web3,personal", "--http.corsdomain", "*"]