version: "3.9"

services:
  geth-devnet:
    #For local tests I was using geth:test image
    image: geth:test
    #image: ghcr.io/${GITHUB_REPOSITORY_OWNER:-your-user}/geth-dev:latest
    container_name: geth-devnet
    ports:
      - "8545:8545"
      - "30303:30303"
    volumes:
      - geth-data:/home/geth/.ethereum
    command:
      [
        "--dev",
        "--http",
        "--http.addr", "0.0.0.0",
        "--http.api", "eth,net,web3,personal",
        "--http.corsdomain", "*"
      ]
volumes:
  geth-data: