name: CI Deploy

on:
  pull_request:
    types: [closed]

jobs:

  deploy:
    if: contains(github.event.pull_request.labels.*.name, 'CI:Deploy') && github.event.pull_request.merged == true

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" \
          | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Start Devnet
        run: |
          docker compose -f docker/docker-compose.yml up -d
          echo "Waiting for RPC..."
          for i in {1..10}; do
            if curl -s http://localhost:8545 > /dev/null; then
              echo "RPC is ready"
              break
            fi
            sleep 3
          done
          
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
              
      - name: Install Hardhat
        run: |
          cd hardhat
          npm install

      - name: Deploy Contracts
        run: |
          working-directory: hardhat
          npx hardhat run scripts/deploy.js --network localhost

      - name: Stop Devnet
        run: docker compose -f docker/docker-compose.yml down

      - name: Build Predeployed Image
        run: |
          docker build \
            -t ghcr.io/${{ github.repository_owner }}/geth-dev:predeployed \
            -t ghcr.io/${{ github.repository_owner }}/geth-dev:predeployed-${{ github.sha }} \
            -f docker/Dockerfile.predeployed .

      - name: Run Devnet With Predeployed Contracts
        run: |
          docker run -d -p 8545:8545 \
          ghcr.io/${{ github.repository_owner }}/geth-dev:predeployed

      - name: Run Hardhat Tests
        run: |
          cd hardhat
          npx hardhat test --network localhost

      - name: Push Image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/geth-dev:predeployed
